name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "**/*.xml"
      - "**/*.java"
      - "**/*.gradle"
      - ".github/workflows/android.yml"
  pull_request:
    paths:
      - "**/*.xml"
      - "**/*.java"
      - "**/*.gradle"
      - ".github/workflows/android.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: app\release\app-release.apk
